### PR TITLE
More color schemes (Win2k, Win98)

### PR DESCRIPTION
**Pull request by chungy**
Two new CSS files to match the color schemes of Windows 98 (titlebar gradient is the difference) and 2000. I've also changed the font definitions so that we can use reasonable sans serif fonts when MS Sans Serif is unavailable (as it is on my system)

### CODE REVIEW

**Comment by Athari** [comment]
Good changes, thanks.

I need to add a proper build system first though, as having 3 copy-pasted files makes the code hard to maintain. On top of that, Stylus and Stylish use different approaches for settings and having 3 separate output files is only practical for extensions supporting .user.css convention.

The missing `sans-serif` fallback is a bug though, I'll fix it right away.

**Comment by chungy** [comment]
Indeed, I could possibly whip up something very quickly with Make and a bit of shell scripting to make it easy to change colors and fonts, and integrate it into a final stylesheet (would also make it easy to convert the whole swath of classic Windows schemes, from 95/98/2000/Me).

It's your project though, and I'm guessing from the use of "MS Sans Serif" that you use Windows (I don't), so maybe that's not the ideal solution :)

**Comment by Athari** [comment]
I'd definitely prefer something cross-platform. 😁 Looks like anything that involves web relies on NodeJS and its tools nowadays, so I guess I need to learn how to get this thing running.

**Comment by Athari** [comment]
Obsoleted by pull request #10.

**Pull request closed without merging**
